# DO NOT DELETE: Beginning of Haskell dependencies
Data.o : Data.hs
Random.o : Random.hs
Random.o : Data.hi
Utils4all.o : Utils4all.hs
Utils4all.o : Data.hi
Changes.o : Changes.hs
Changes.o : Utils4all.hi
Changes.o : Data.hi
Show.o : Show.hs
Show.o : Utils4all.hi
Show.o : Data.hi
Utils4stuff.o : Utils4stuff.hs
Utils4stuff.o : Changes.hi
Utils4stuff.o : Data.hi
Utils4mon.o : Utils4mon.hs
Utils4mon.o : Changes.hi
Utils4mon.o : Utils4stuff.hi
Utils4mon.o : Utils4all.hi
Utils4mon.o : Data.hi
Stuff.o : Stuff.hs
Stuff.o : Utils4mon.hi
Stuff.o : Utils4all.hi
Stuff.o : Utils4stuff.hi
Stuff.o : Data.hi
Utils.o : Utils.hs
Utils.o : Utils4mon.hi
Utils.o : Utils4all.hi
Utils.o : Changes.hi
Utils.o : Utils4stuff.hi
Utils.o : Stuff.hi
Utils.o : Data.hi
Object.o : Object.hs
Object.o : Utils4all.hi
Object.o : Changes.hi
Object.o : Utils.hi
Object.o : Data.hi
AI.o : AI.hs
AI.o : Changes.hi
AI.o : Utils4all.hi
AI.o : Object.hi
AI.o : Utils.hi
AI.o : Data.hi
Monsters.o : Monsters.hs
Monsters.o : Utils4all.hi
Monsters.o : AI.hi
Monsters.o : Random.hi
Monsters.o : Stuff.hi
Monsters.o : Data.hi
Step.o : Step.hs
Step.o : Utils4mon.hi
Step.o : Utils4all.hi
Step.o : Changes.hi
Step.o : Monsters.hi
Step.o : Object.hi
Step.o : Utils.hi
Step.o : Data.hi
Main.o : Main.hs
Main.o : Show.hi
Main.o : Changes.hi
Main.o : Step.hi
Main.o : Monsters.hi
Main.o : Data.hi
Main.o : Utils.hi
# DO NOT DELETE: End of Haskell dependencies
